### ISSUE TITLE
Allow node_modules dir to be included in files for review

### ISSUE THREAD

**Issue by bebbs** [jfmengels/node-elm-review#12]
**Background**

We use an internal npm package hosted on a private registry to share some private Elm modules between projects without publishing them on the Elm package registry. We add `./node_modules/our/package` to each projects `source-directories` list, and therefore any elm dependency of those shared modules must also be added to each projects elm.json dependencies list.

I'm looking at implementing elm-review on all of our projects, and would like to add `NoUnused.Dependencies` from [jfmengels/review-unused](https://github.com/jfmengels/review-unused) to catch any non-required dependencies.

**Issue**

The `NoUnused.Dependencies.rule` fails and claims that dependencies used only by elm modules from `./node_modules/our/package`, and thus included in each projects `elm.json`, are unused, whilst in reality they are used and required for the compiler to succeed.

From a look at `node-elm-review`, I think that rule is failing because there are some (reasonable) assumptions baked in to ignore anything under `node_modules`. I believe that if those assumptions were not there, the rule would not fail for our use case, as elm code under `node_modules` could be treated the same as code in any other directory.

I realise that the current behaviour is suitable for most users of `elm-review`, and our use case is pretty niche, but would a patch that makes it possible to include elm under `node_modules` for review be welcomed?

One approach might be to make the `ignore` constant in `elm-files.js` configurable by a command line flag:  
https://github.com/jfmengels/node-elm-review/blob/master/lib/elm-files.js#L13

**Comment by jfmengels** [comment]
Hi @bebbs :wave: 

Thank you for the detailed explanation :pray: 

This was done just as a potential performance optimization, which I know think isn't all that necessary, as I think it's pretty rare to have `node_modules` inside your Elm source directories.

I have heard of this method used in some other place (I can't remember where though), so it might not be all that niche.

I have just patched the code and pushed it on `master`. Could you try it out and see if that resolves your problem?
I tried it out on a few projects of mine and it doesn't seem to impact the performance (because there are no `node_modules` in there also).

Also, let me know if you run into any trouble trying out a local version, that will me help set up a "how to contribute" document. I think that you'll be fine by checking out the branch, running `npm install && npm run build` then using the binary at `bin/elm-review`.

**Comment by bebbs** [comment]
Appreciate the quick response @jfmengels, thank you 🙌 

I've tried that change out and it does solve our issue. Those instructions for building and running locally also worked exactly as you described.

**Comment by jfmengels** [comment]
Fixed and published in v2.2.1 of the CLI :slightly_smiling_face:
