### ISSUE TITLE
Make test script in GitHub workflow work with other npm package managers

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/node-elm-review#21]
In the maintenance document, we mention that users can install their npm dependencies using `npm` or `yarn`, but the test script in the CI only works with npm since it uses [`npm ci`](https://github.com/jfmengels/node-elm-review/blob/master/new-package/github/workflows/test.yml#L22).

Also, I noticed that @avh4 uses `pnpm`, and for him the tests failed for this very same reason.

I think the CI could reasonably run `npm ci` or `yarn` or `pnpm install` by detecting the presence of `package-lock.json`, `yarn.json` and/or `pnpm-lock.yaml` file respectively.

**Comment by avh4** [comment]
I will add that while I often use `pnpm` locally when developing, I still typically use `npm` on CI.  I was just pushing the boundaries a bit on that experimental project.

Though on the use of `npm`, for small open-source packages (like elm-review rules), personally I would not be checking in a `package-lock.json` and would use `npm install` instead of `npm ci` because I prefer my CI to notify me early when something with a new version of a dependency breaks.
