### ISSUE TITLE
NoUnused.Variables reports wrong alias as unused when importing module from elm-git-install dependency

### ISSUE THREAD

**Issue by morteako** [jfmengels/node-elm-review#320]
**Describe the bug**
When importing two modules as the same alias, and one of the modules comes from a package installed by elm-git-install, NoUnused.Variables reports the used module as unused, and the unused as used.

**SSCCE (Short Self-Contained Correct Example)**
1. Clone https://github.com/morteako/elm-review-test-case : `git clone git@github.com:morteako/elm-review-test-case.git`
1.5. optional: The results from running elm-git-install is already included in the repo, but
if one wants or needs (if issues) to actually run `elm-git-install`, just run `rm -rf elm-stuff && npx elm-git-install` and it will overwrite the contents if needed.
2. Run `npx elm-review`
3. See wrong first error and correct second error
4. Check out source code in src/ and https://github.com/morteako/elm-review-test-case/blob/master/elm-stuff/gitdeps/github.com/morteako/elm-review-test-case-git-install.git/src/ if one would like

**Expected behavior**
I expect elm-review and NoUnused.Variables to report the correct module alias as unused, namely: `import UtilNotUsed as List`

**Additional context**
Code that triggers the bug, where Util.List is installed in elm-stuff, using elm-git-install
```elm
module MainGitInstallWrongError exposing (..)

-- actually used, reported as unused
import Util.List as List

-- actually unused, not reported as unused
import UtilNotUsed as List

useImportAliasFromElmstuff x = List.test x
```

The actually unused module does not contain a `test`-export
```elm
module UtilNotUsed exposing (x)

x = 1
```

The module installed using elm-git-install can be seen here:
It does export `test` and is the therefore the module alias that is actually used
https://github.com/morteako/elm-review-test-case/blob/master/elm-stuff/gitdeps/github.com/morteako/elm-review-test-case-git-install.git/src/Util/List.elm

and contains 
```elm
module Util.List exposing (test)

test : a -> a
test x = x
```

To see full code, see [repo](https://github.com/morteako/elm-review-test-case)

I can't reproduce the bug when import two local modules instead (see https://github.com/morteako/elm-review-test-case/blob/master/src/MainLocalCorrectError.elm), so it seems to be related to elm-git-install and the fact that it places the code in elm-stuff/gitdeps/github.com/...

I have not had any other bugs like this related to elm-git-install packages and elm-review though.

**Comment by jfmengels** [comment]
Hi @morteako

FIrst of all, thank you for an amazingly well-written and helpful issue and SSCCE, this is lovely for me to work with :heart:

The issue seems to stem from the fact some of your Elm files - in this case the ones from `elm-git-install` - as it ignores files from `elm-stuff`. Do you know if this is a common pattern, or maybe even the default behavior for `elm-git-install`? (I have no experience with the tool).

I think it is do-able to be more precise in the ignored files in the CLI, so that we only ignore `elm-stuff` in each source-directory, and not all `elm-stuff`.

In case you're curious as to why you found this out with this rule: when an Elm file is somehow not found, then it becomes impossible to figure out where `List.test` comes from, so it tries to guess a random one (the last one it seems). That made the first import aliased to `List` look like it was unused.

**Comment by morteako** [comment]
> Do you know if this is a common pattern, or maybe even the default behavior for elm-git-install? (I have no experience with the tool).
Yes, it is the default behaviour and also non-configurable it seems 😅 

Ah, that makes sense. 
I tried now by moving the folder and changing the source-directory, and then the error msg was correct.

Regarding the guessing. Could it then be better to not report anything?
I haven't thought it through, and maybe the guess is correct in nearly every case.
But if not, it could maybe be better to have no error instead of a false positive?

I see that you already have made a PR. 
Amazing productivity and response time 🚀
