### ISSUE TITLE
CLI output is hard to read on a light colour background

### ISSUE THREAD

**Issue by alexkorban** [jfmengels/node-elm-review#63]
I use white background in the terminal, and I'm unable to read the parts of the CLI output which are in yellow (and cyan is not easy to read either). I couldn't find any way to configure or disable the colours. Other colours are OK. 

I'm using elm-review 2.6.1.

**Comment by jfmengels** [comment]
Hey @alexkorban

Sorry about that! You can use the `--no-color` flag to disable colouring. I'll try to figure out whether I can change yellow and cyan for colors that work better.

I was wondering whether I could detect the background color, and if it is white, then choose different colors for those 2 (and maybe more). But I imagine that that is not a viable solution because people can choose myriads of background colors, not just black or white.

I'd love help from someone with better design skills than mine :smile:

**Comment by alexkorban** [comment]
Oh good, I can disable colours for now. Perhaps the easiest option is to use colours which work on light and dark backgrounds - red, magenta, lighter blue etc. I can take a look at what colours could be used instead of yellow and cyan and report back.

**Comment by alexkorban** [comment]
Made a PR with proposed colour changes.

**Comment by jfmengels** [comment]
Solved in https://github.com/jfmengels/node-elm-review/pull/64
