### ISSUE TITLE
Use elm-solve-deps-wasm instead of elm-json

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/node-elm-review#81]
This has been mentioned in other issues in this repository, like https://github.com/jfmengels/node-elm-review/issues/51 and https://github.com/jfmengels/node-elm-review/issues/61#issuecomment-1023483505

I think this has been shipped to `node-elm-test` (https://github.com/rtfeldman/node-test-runner/pull/558/) and I haven't heard problems about it.

@mpizenberg @lydell do you know whether `elm-solve-deps-wasm` is capable of doing all the things that `elm-review` currently requires `elm-json` for?

- Solving dependencies, like in https://github.com/jfmengels/node-elm-review/blob/a406f60c91790affdfc1f6cd31217c2fd02982e6/lib/template-dependencies.js#L40-L46
- Installing dependencies https://github.com/jfmengels/node-elm-review/blob/a406f60c91790affdfc1f6cd31217c2fd02982e6/lib/template-dependencies.js#L127-L144 (used for `elm-review init`). I guess that a way to get the latest compatible versions of packages would work as well.
- Upgrading dependencies https://github.com/jfmengels/node-elm-review/blob/a406f60c91790affdfc1f6cd31217c2fd02982e6/lib/template-dependencies.js#L150 This is used when using `--template` with a package that uses an out of date and incompatible `elm-review` version. To avoid asking every package author to update their configuration all the time, `elm-review` upgrades the version of the dependencies.

Is there anything else that you think I should know about this package?

Also, if one of you happens to be motivated by working on this, that would be amazing. I'm not sure when I would get to this myself.

**Comment by mpizenberg** [comment]
The best summary of what elm-solve-deps-wasm is capable of is available in this message: https://github.com/rtfeldman/node-test-runner/pull/558#issuecomment-1089427756
As the name suggests, this is just a solver, that also needs the caller to provide a way to fetch dependencies (either locally or remotely). If you copy the surrounding logic from node-test-runner, you get the following API:
```js
// same interface for solveOnline
solveOffline( 
  elmJson /*: string */,
  useTest /*: boolean */,
  extra /*: { [string]: string } */
) /*: string */ { ... }
```

So this seems to be a direct solution for your first need. Unfortunately, it doesn't handle the "installing" part of your needs. Installing is a bit more work because it has both (1) a solving part, and (2) a re-arrange the set of dependencies found into normal/test direct/indirect sections. That normal/test sections separation is not dealt with in elm-solve-deps-wasm. And it's not dealt with either in elm-test-rs. I still have a message their saying something like "If you want to install/remove/upgrade dependencies, I suggest using the elm-json tool".

**Comment by mpizenberg** [comment]
As for the "upgrade" command, I don't know its semantics, so I can't comment on it.

**Comment by lydell** [comment]
So, to me it sounds like:

- Solving is a solved problem
- Installing and upgrading needs some investigation

I would love to see this in elm-review, and also so I can remove the whole “use this to depend on a binary” thing from elm-tooling. But at least for the coming months I’d like to focus on other things.
