### ISSUE TITLE
I tried npx elm-review init -> issue

### ISSUE THREAD

**Issue by jarmol** [jfmengels/node-elm-review#84]
Hi Jeroen
I would like to try elm-review.
I can do global install only if logged in as privileged user like this.
sudo -s
npm i elm-review -g

Alternatively as non-privileged user about all in elm locally (not global) like this.
elm install elm-review
I have already tried to install in both ways but it failed.
Now I tried usind npx without success. 
I wonder, did I something wrong in the following?
Can you help? (I am alias Polarit in discourse.elm-lang.org)
I made just this:
jarmo$ npx elm-review init
✔ Would you like me to create elm.json and src/ReviewConfig.elm inside /jarmo/elmlang/newproject/review? … yes
-- UNEXPECTED ERROR ------------------------------------------------------------

I ran into an unexpected error. Please open an issue at the following link:
  https://github.com/jfmengels/node-elm-review/issues/new

Below is the error that was encountered.
--------------------------------------------------------------------------------
Error: elm-json exited with exit code 1
    at ChildProcess.<anonymous> (/jarmo/.npm/_npx/e2fd655fbe81d361/node_modules/elm-review/lib/template-dependencies.js:221:27)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:686:12)

However, directory src and  elm-json was created within review.
jarmo$ ll review/
total 8
drwxr-xr-x  2 jarmo  staff   64 27 Syy 21:46 src
-rw-r--r--  1 jarmo  staff  260 27 Syy 21:46 elm.json
MacBook-Air:newproject jarmo$ 
There is nothing about elm-review on the upper level elm.json, neither in the directory review elm.json
newproject jarmo$ cat review/elm.json 
{
    "type": "application",
    "source-directories": [
        "src"
    ],
    "elm-version": "0.19.1",
    "dependencies": {
        "direct": {},
        "indirect": {}
    },
    "test-dependencies": {
        "direct": {},
        "indirect": {}
    }

Shall I remove first elm.json on the upper level abowe directory review and then run
elm init 
or which way?

I have already long time used nodejs and npm installed and I work  in bash shell of Apple macos.

Best regards, Jarmo

**Comment by jfmengels** [comment]
Hi @jarmol

I'm sorry to see you encountering issues with this. It's usually not a good idea to run nodejs with `sudo`, because that has some security concerns and I have seen it create problems similar to this, though I'm not sure this is the cause. If you need to use nodejs as the super user, it's probably because you installed nodejs as a super user.

The way to install elm-review is `npm install elm-review` (possibly with `-g`), not `elm install elm-review`.

I have trouble understanding why you're getting this error. It seems that it could not find `elm-json` (the tool, not to be confused with the `elm.json` file). Maybe it's because nodejs is run as the super user, maybe not.

Could you try also installing `elm-json` globally (`npm i -g elm-json`), and then trying `elm-review init` again. Do remove the whole `review/` folder before you try this again.

If this doesn't work, then try to do the following
- Remove the `review/` folder (if you still have it)
- Install elm-review and elm-json locally `npm i elm-json elm-review`
- Run elm-review using `npx`: `npx elm-review init`.

Even if it works, this will give you an empty review configuration (you'll have an empty list in your `review/src/ReviewConfig.elm` file though), so I think that the following will be a more useful way for you to try the tool out:
```bash
elm-review init --template jfmengels/elm-review-config/application
```

I hope this works for you or that this gives some more insight.

**Comment by jarmol** [comment]
Hi @jfmengels ,

I have tried about every way so as you suggested but npm i elm-review and elm-reviw init ended always with the same errors :(
I successed installing elm-review in sudo but it did'nt create e.g. the configuration file to src folder (it did create only the folder review and within it the folders src and elm.json)

However, elm.json it created in review folder seems to be now complete!
jarmo$ cat review/elm.json 
{
    "type": "application",
    "source-directories": [
        "src"
    ],
    "elm-version": "0.19.1",
    "dependencies": {
        "direct": {
            "elm/core": "1.0.5",
            "elm/json": "1.1.3",
            "elm/project-metadata-utils": "1.0.2",
            "jfmengels/elm-review": "2.9.0",
            "jfmengels/elm-review-code-style": "1.1.0",
            "jfmengels/elm-review-common": "1.3.0",
            "jfmengels/elm-review-debug": "1.0.6",
            "jfmengels/elm-review-documentation": "2.0.2",
            "jfmengels/elm-review-simplify": "2.0.21",
            "jfmengels/elm-review-unused": "1.1.26",
            "stil4m/elm-syntax": "7.2.9"
        },
        "indirect": {
            "elm/html": "1.0.0",
            "elm/parser": "1.1.0",
            "elm/random": "1.0.0",
            "elm/regex": "1.0.0",
            "elm/time": "1.0.0",
            "elm/virtual-dom": "1.0.3",
            "elm-community/list-extra": "8.6.0",
            "elm-explorations/test": "1.2.2",
            "miniBill/elm-unicode": "1.0.2",
            "pzp1997/assoc-list": "1.0.0",
            "rtfeldman/elm-hex": "1.0.0",
            "stil4m/structured-writer": "1.0.3"
        }
    },
    "test-dependencies": {
        "direct": {
            "elm-explorations/test": "1.2.2"
        },
        "indirect": {}
    }
}

I'm sure now, it's no issue of your stuff atall, but the reason is just the way I have installed node and elm things. Thus I'll close this issue as Done!

- Jarmo
[to_JF_Mengels.txt](https://github.com/jfmengels/node-elm-review/files/9666426/to_JF_Mengels.txt)
[to_JF_Mengels.txt](https://github.com/jfmengels/node-elm-review/files/9666430/to_JF_Mengels.txt)

**Comment by jfmengels** [comment]
Alright! I'm glad it worked out for you! Thank you for letting me know
