### ISSUE TITLE
`Fixed 0 issue so far` should be `Fixed 0 issues so far`

### ISSUE THREAD

**Issue by MartinSStewart** [jfmengels/node-elm-review#99]
The text `Fixed 0 issue so far` that appears in the terminal when elm-review is running should be plural not singular for 0 errors.

**Comment by MartinSStewart** [comment]
Oh also, after elm-review finished it wrote
```
√ Do you wish to apply the result of these 0 fixes? ... yes
I found no more errors!
```
despite having fixed several things.

**Comment by jfmengels** [comment]
The `Fixed 0 issue so far` is a bug that should not happen in the first place, it should always at least say 1 error. I think I may have fixed some of the places where this shows up, but if you notice it still (with v2.12.0 of `jfmengels/elm-review`) then let me know (in a different issue, and ideally with a SSCCE because I'm having trouble reproducing it ^_^' ).

**Comment by jfmengels** [comment]
I'll close this issue since I won't be doing anything directly about it. Thanks for reporting this though!

**Comment by MartinSStewart** [comment]
I'm unfortunately too busy to make an SSCCE right now but if I continue running into it then I'll make another issue with an SSCCE
